---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: windows-2012R2
    driver:
      username: administrator
      password: Pass@word1
      guest: :windows
      box: mwrock/Windows2012R2
      vagrantfile_erb: VagrantfileWinrm.erb
      provider: hyperv
      box_url: https://vagrantcloud.com/mwrock/Windows2012R2/version/1/provider/hyperv.box

suites:
  - name: default
    run_list:
      - recipe[boxstarter::default]
    attributes:
